# Generated by Django 6.0.3 on 2026-04-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0012_cart_size_orderitem_size_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sizes',
            field=models.CharField(blank=True, help_text='Comma-separated sizes e.g., S,M,L,XL', max_length=100),
        ),
    ]
