# Generated by Django 6.0.3 on 2026-04-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0013_products_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, default='M', max_length=5, null=True),
        ),
    ]
